### ISSUE TITLE
Clarify meaning of Stats.GradientNorm

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/optimize#41]
* Is it the norm at the best location so far? Then it should be updated only when optLoc is updated and it makes sense to keep it in Stats.
* Is it the norm at the latest location? Then it should be updated at every iteration and it makes sense to move it to Location.

**Comment by btracey** [comment]
I think the first. I think I had it there was because it's useful information to have at the result, and it needs to exist somewhere to check the norm of the gradient for convergence. However, we return the full gradient in Result anyway (in Location), and it's cheap and easy for the user to compute (now that we guarantee the infinity norm). It doesn't need to be in Stats for any reason. For reasons discussed elsewhere, we only want to be checking the gradient norm  on the optimum anyway.

**Comment by vladimir-ch** [comment]
OK, let's remove it from Stats. We have to update the docs (oops, the comment for Stats.GradientAbsTol is completely out of date).

**Comment by vladimir-ch** [comment]
Question answered, PR submitted, closing.
